version: '2'
services:
    cloudsqlproxy:
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        volumes:
            - /opt/app/cloudsql:/cloudsql
            - ~/umg-dev-key.json:/config
        ports:
            - '127.0.0.1:3306:3306'
        command: /cloud_sql_proxy -instances=umg-dev:us-central1:umg-swift-cloud-sql=tcp:0.0.0.0:3306 -credential_file=/config 
    